language: ruby

services:
  - docker

install:
  - echo 'No install needed; Docker will take care of this.'

before_script:
  - docker-compose up

script:
  - docker exec erogatio_web_1 bundle exec rspec
  - docker exec erogatio_web_1 bundle exec cucumber
