language: generic # see https://medium.com/@desfocado/how-to-get-travis-to-work-with-no-build-language-9f4c03ed68b1

services:
  - docker

env:
  - DOCKER_APP_DB_USERNAME=erogatio DOCKER_APP_DB_PASSWORD=password DOCKER_POSTGRES_PASSWORD=sekrit

install:
  - /bin/true

before_script:
  - docker-compose up -d

script:
  - docker exec erogatio_web_1 bundle exec rspec
  - docker exec erogatio_web_1 bundle exec cucumber
