version: '3'
networks:
  internal:
    driver: bridge
services:
  web:
    environment:
      PORT: 3000
    build: .
    depends_on: [db]
    environment:
      APP_DB_USERNAME: ${DOCKER_APP_DB_USERNAME}
      APP_DB_PASSWORD: ${DOCKER_APP_DB_PASSWORD}
    volumes: [".:/erogatio"]
    ports: ["3000:3000"]
    networks: [internal]
    command: ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
  db:
    build:
      context: .
      dockerfile: db.dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DOCKER_POSTGRES_PASSWORD}
      APP_DB_USERNAME: ${DOCKER_APP_DB_USERNAME}
      APP_DB_PASSWORD: ${DOCKER_APP_DB_PASSWORD}
    volumes: [".pgdata:/var/lib/postgresql/data"]
    expose: ["5432"]
    networks: [internal]
